---
abstract: 'Mojolicious server for AWS Lambda'
author:
  - 'Prajith P <me@prajith.in>'
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.014, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-Server-AWSLambda
requires:
  JSON::Types: '0'
  Mojolicious: '0'
  Try::Tiny: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/Prajithp/P5-Mojo-Server-AWSLambda/issues
  repository: https://github.com/Prajithp/P5-Mojo-Server-AWSLambda.git
version: '0.01'
x_generated_by_perl: v5.18.2
x_serialization_backend: 'YAML::Tiny version 1.70'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
